### ISSUE TITLE
Posting to Private Repositories

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/comment-incentives#5]
I'm assuming this crashed because AXIOS doesn't support GitHub authentication. Perhaps the comment should be posted with authenticated Octokit instead. 

> ```diff
> + Evaluating results. Please wait...
> ```

https://github.com/ubiquibot/comment-incentives/actions/runs/7694293618/job/20964796364 @wannacfuture not sure what happened here.

_Originally posted by @pavlovcik in https://github.com/ubiquity/card-issuance/issues/9#issuecomment-1914368825_

**Comment by FernandVEYRIER** [comment]
@pavlovcik from what I see here, it's because the axios call tried to reach the `card-issuance` repository which is indeed private, so got a 404. Any reason that the comments are parsed from the web page instead of using Octokit to access them?
I believe the fix is to replace these fetch of pull request comments with Octokit calls, and use the GitHub token from the Action to authenticate.

**Comment by pavlovcik** [comment]
Honestly I have mixed feelings about continuing to invest in this repository because i hit a milestone with the next version. 

However it might be worthwhile to get familiar with the code and then perhaps get familiar with the [new version](https://t.me/UbiquityDAO/29891/31924) as well. 

I took an entirely authenticated approach. It's not usable yet though because all it does is collect all the user activity. 

The next part will be to calculate the comment incentives. Although I would like to take that as far as I can this week before preparing new issues and handing it off.
